/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness. `async` so it is answered on the event loop, even while simulations fill the threads.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Presets
         * @description Every preset in shared/presets, plus the calibration profiles.
         */
        get: operations["get_presets_api_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Templates
         * @description The starter designs, exactly as the files in shared/templates have them.
         */
        get: operations["get_templates_api_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Design
         * @description `{design, config?}` → every issue (§7.6, and §3's run limits when `config` is sent). Always 200.
         */
        post: operations["validate_design_api_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Design
         * @description `{design, config}` → the RunResult (§7.4), or 422 with the issues, 429 or 504.
         */
        post: operations["simulate_design_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgentNode: {
            id: string;
            label: string;
            position: components["schemas"]["Position"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "agent";
            params: components["schemas"]["AgentParams"];
        };
        AgentParams: {
            llmCallsMean: number;
            toolCallsPerStep: number;
            toolLatency: components["schemas"]["LatencyDist"];
            basePromptTokens: number;
            contextGrowthTokensPerStep: number;
            outputTokensPerCall: number;
        };
        AttributionRow: {
            nodeId: string;
            queueShare: number;
            workShare: number;
        };
        Bottleneck: {
            /** @enum {string} */
            severity: "info" | "warn" | "critical";
            nodeId?: string;
            message: string;
        };
        CacheNode: {
            id: string;
            label: string;
            position: components["schemas"]["Position"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "cache";
            params: components["schemas"]["CacheParams"];
        };
        CacheParams: {
            hitRate: number;
            latency: components["schemas"]["LatencyDist"];
            costPerMonth: number;
        };
        ConstantTraffic: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "constant";
            rps: number;
        };
        Cost: {
            monthlyTotalUsd: number;
            breakdown: components["schemas"]["CostLine"][];
            assumptions: string[];
        };
        CostLine: {
            nodeId: string;
            usd: number;
            detail: string;
        };
        DatabaseNode: {
            id: string;
            label: string;
            position: components["schemas"]["Position"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "database";
            params: components["schemas"]["DatabaseParams"];
        };
        DatabaseParams: {
            /** @enum {string} */
            preset: "postgres" | "mongodb" | "vector" | "custom";
            connectionPool: number;
            queueLimit: number;
            query: components["schemas"]["LatencyDist"];
            costPerMonth: number;
        };
        Design: {
            id?: string;
            name: string;
            /** @constant */
            version: 1;
            nodes: (components["schemas"]["UsersNode"] | components["schemas"]["LoadBalancerNode"] | components["schemas"]["ServiceNode"] | components["schemas"]["CacheNode"] | components["schemas"]["DatabaseNode"] | components["schemas"]["AgentNode"] | components["schemas"]["LlmNode"])[];
            edges: components["schemas"]["DesignEdge"][];
        };
        DesignEdge: {
            id: string;
            source: string;
            target: string;
            /** @enum {string} */
            role?: "llm" | "tool";
        };
        Engine: {
            events: number;
            wallMs: number;
            eventsPerSec: number;
            simulatedRequests: number;
        };
        GpuPoint: {
            t: number;
            kvPct: number;
            batch: number;
            waiting: number;
        };
        GpuSeries: {
            nodeId: string;
            points: components["schemas"]["GpuPoint"][];
        };
        HostedLlmParams: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "hosted";
            presetId: string;
            ttft: components["schemas"]["LatencyDist"];
            tokensPerSecond: components["schemas"]["TokensPerSecond"];
            inputUsdPer1M: number;
            outputUsdPer1M: number;
            rateLimitRpm: number;
            maxRetries: number;
        };
        /** @description A lognormal latency given by its median and 99th percentile, in milliseconds (§8.3). */
        LatencyDist: {
            p50Ms: number;
            p99Ms: number;
        };
        LatencySummary: {
            p50: number;
            p95: number;
            p99: number;
            max: number;
        };
        LlmNode: {
            id: string;
            label: string;
            position: components["schemas"]["Position"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "llm";
            params: components["schemas"]["HostedLlmParams"] | components["schemas"]["SelfHostedLlmParams"];
        };
        LoadBalancerNode: {
            id: string;
            label: string;
            position: components["schemas"]["Position"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "loadBalancer";
            params: components["schemas"]["LoadBalancerParams"];
        };
        LoadBalancerParams: {
            /** @enum {string} */
            algorithm: "roundRobin" | "leastConnections";
            overhead: components["schemas"]["LatencyDist"];
        };
        NodePoint: {
            util: number;
            queue: number;
            rejects: number;
            throughputRps: number;
        };
        NodeSummary: {
            id: string;
            /** @enum {string} */
            kind: "users" | "loadBalancer" | "service" | "cache" | "database" | "agent" | "llm";
            utilAvg: number;
            utilMax: number;
            queueAvg: number;
            queueMax: number;
            rejects: number;
            monthlyUsd: number;
        };
        Percentiles: {
            p50: number;
            p95: number;
            p99: number;
        };
        Position: {
            x: number;
            y: number;
        };
        RampTraffic: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ramp";
            startRps: number;
            endRps: number;
        };
        RunConfig: {
            durationS: number;
            seed: number;
            /** @default 5 */
            warmupS: number;
        };
        RunResult: {
            runId?: string;
            designHash: string;
            config: components["schemas"]["RunConfig"];
            engine: components["schemas"]["Engine"];
            summary: components["schemas"]["Summary"];
            timeline: components["schemas"]["TimelinePoint"][];
            nodes: components["schemas"]["NodeSummary"][];
            gpu: components["schemas"]["GpuSeries"][];
            attribution: components["schemas"]["AttributionRow"][];
            cost: components["schemas"]["Cost"];
            bottlenecks: components["schemas"]["Bottleneck"][];
        };
        SelfHostedLlmParams: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "selfHosted";
            gpuPresetId: string;
            modelPresetId: string;
            profileId: string;
            replicas: number;
            maxBatchSize: number;
            maxBatchTokens: number;
            maxOutputTokensReserve: number;
            speculative: components["schemas"]["Speculative"];
        };
        ServiceNode: {
            id: string;
            label: string;
            position: components["schemas"]["Position"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "service";
            params: components["schemas"]["ServiceParams"];
        };
        ServiceParams: {
            replicas: number;
            concurrencyPerReplica: number;
            queueLimit: number;
            work: components["schemas"]["LatencyDist"];
            costPerReplicaMonth: number;
        };
        /** @description Speculative decoding. The other fields are only checked when it is enabled. */
        Speculative: {
            enabled: boolean;
            draftTokens: number;
            acceptanceRate: number;
            draftStepMs: number;
        };
        SpikeTraffic: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "spike";
            baseRps: number;
            peakRps: number;
            peakStartS: number;
            peakDurationS: number;
        };
        Summary: {
            requests: number;
            completed: number;
            errors: number;
            timeouts: number;
            rejected: number;
            throughputRps: number;
            errorRate: number;
            latencyMs: components["schemas"]["LatencySummary"];
            ttftMs?: components["schemas"]["Percentiles"];
        };
        TimelinePoint: {
            t: number;
            arrivalsRps: number;
            throughputRps: number;
            errorRate: number;
            p50: number;
            p95: number;
            p99: number;
            nodes: {
                [key: string]: components["schemas"]["NodePoint"];
            };
        };
        /** @description Generation speed: the median and the slow 1st percentile (§8.3). */
        TokensPerSecond: {
            p50: number;
            p99Low: number;
        };
        UsersNode: {
            id: string;
            label: string;
            position: components["schemas"]["Position"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "users";
            params: components["schemas"]["UsersParams"];
        };
        UsersParams: {
            traffic: components["schemas"]["ConstantTraffic"] | components["schemas"]["SpikeTraffic"] | components["schemas"]["RampTraffic"];
            clientTimeoutMs: number;
        };
        ValidationErrorBody: {
            issues: components["schemas"]["ValidationIssue"][];
        };
        ValidationIssue: {
            code: string;
            message: string;
            nodeId?: string;
            edgeId?: string;
            path?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AgentNode = components['schemas']['AgentNode'];
export type AgentParams = components['schemas']['AgentParams'];
export type AttributionRow = components['schemas']['AttributionRow'];
export type Bottleneck = components['schemas']['Bottleneck'];
export type CacheNode = components['schemas']['CacheNode'];
export type CacheParams = components['schemas']['CacheParams'];
export type ConstantTraffic = components['schemas']['ConstantTraffic'];
export type Cost = components['schemas']['Cost'];
export type CostLine = components['schemas']['CostLine'];
export type DatabaseNode = components['schemas']['DatabaseNode'];
export type DatabaseParams = components['schemas']['DatabaseParams'];
export type Design = components['schemas']['Design'];
export type DesignEdge = components['schemas']['DesignEdge'];
export type Engine = components['schemas']['Engine'];
export type GpuPoint = components['schemas']['GpuPoint'];
export type GpuSeries = components['schemas']['GpuSeries'];
export type HostedLlmParams = components['schemas']['HostedLlmParams'];
export type LatencyDist = components['schemas']['LatencyDist'];
export type LatencySummary = components['schemas']['LatencySummary'];
export type LlmNode = components['schemas']['LlmNode'];
export type LoadBalancerNode = components['schemas']['LoadBalancerNode'];
export type LoadBalancerParams = components['schemas']['LoadBalancerParams'];
export type NodePoint = components['schemas']['NodePoint'];
export type NodeSummary = components['schemas']['NodeSummary'];
export type Percentiles = components['schemas']['Percentiles'];
export type Position = components['schemas']['Position'];
export type RampTraffic = components['schemas']['RampTraffic'];
export type RunConfig = components['schemas']['RunConfig'];
export type RunResult = components['schemas']['RunResult'];
export type SelfHostedLlmParams = components['schemas']['SelfHostedLlmParams'];
export type ServiceNode = components['schemas']['ServiceNode'];
export type ServiceParams = components['schemas']['ServiceParams'];
export type Speculative = components['schemas']['Speculative'];
export type SpikeTraffic = components['schemas']['SpikeTraffic'];
export type Summary = components['schemas']['Summary'];
export type TimelinePoint = components['schemas']['TimelinePoint'];
export type TokensPerSecond = components['schemas']['TokensPerSecond'];
export type UsersNode = components['schemas']['UsersNode'];
export type UsersParams = components['schemas']['UsersParams'];
export type ValidationErrorBody = components['schemas']['ValidationErrorBody'];
export type ValidationIssue = components['schemas']['ValidationIssue'];
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown[];
                    };
                };
            };
        };
    };
    get_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Design"][];
                };
            };
        };
    };
    validate_design_api_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorBody"];
                };
            };
        };
    };
    simulate_design_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description The design can't run as it is. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorBody"];
                };
            };
        };
    };
}
